import type {
  GrowthTrendPoint,
  OnboardingFunnelData,
  RegionalDiagnosticRecord,
  SellingAgentRecord,
  GrowthAnomalyAlert,
} from '../models/types'

export const mockMonthlyGrowthTrend: GrowthTrendPoint[] = [
  { date: 'Jan 2026', registered: 190, verified: 160, activated: 50, cohortGmv: 140000000 },
  { date: 'Feb 2026', registered: 230, verified: 190, activated: 65, cohortGmv: 182000000 },
  { date: 'Mar 2026', registered: 280, verified: 240, activated: 78, cohortGmv: 218400000 },
  { date: 'Apr 2026', registered: 310, verified: 270, activated: 92, cohortGmv: 257600000 },
  { date: 'May 2026', registered: 330, verified: 290, activated: 105, cohortGmv: 294000000 },
  { date: 'Jun 2026', registered: 350, verified: 310, activated: 115, cohortGmv: 322000000 },
  { date: 'Jul 2026', registered: 420, verified: 360, activated: 135, cohortGmv: 378000000 },
  { date: 'Aug 2026', registered: 460, verified: 400, activated: 150, cohortGmv: 420000000 },
]

export const mockDailyGrowthTrend: GrowthTrendPoint[] = Array.from({ length: 31 }, (_, i) => {
  const day = i + 1
  const registered = 8 + Math.floor(Math.sin(day / 3) * 4) + (day > 20 ? 8 : 0)
  const verified = Math.floor(registered * 0.88)
  const activated = Math.floor(verified * 0.38)
  const cohortGmv = activated * 2800000
  return {
    date: `Aug ${day}`,
    fullDate: `August ${day}, 2026`,
    registered,
    verified,
    activated,
    cohortGmv,
  }
})

export const mockFunnelData: OnboardingFunnelData = {
  newRegistrants: 2430,
  autoMatched: 1820,
  pendingReview: 610,
  manualApproved: 300,
  verifiedTotal: 2120,
  activatedTotal: 726,
  pendingFirstOrder: 1394,
}

export const mockRegionalDiagnostics: RegionalDiagnosticRecord[] = [
  {
    region: 'Jawa Barat',
    groupRegion: 'CPD',
    registered: 620,
    verified: 598,
    verifiedPercent: 96.5,
    pending: 22,
    slaBreachCount: 2,
    slaBreachPercent: 9.1,
    activated: 310,
    activatedPercent: 51.8,
    cohortGmv: 540500000,
  },
  {
    region: 'DKI Jakarta',
    groupRegion: 'CPD',
    registered: 400,
    verified: 392,
    verifiedPercent: 98.0,
    pending: 8,
    slaBreachCount: 0,
    slaBreachPercent: 0.0,
    activated: 210,
    activatedPercent: 53.6,
    cohortGmv: 380000000,
  },
  {
    region: 'Jawa Tengah',
    groupRegion: 'CPD',
    registered: 350,
    verified: 335,
    verifiedPercent: 95.7,
    pending: 15,
    slaBreachCount: 1,
    slaBreachPercent: 6.7,
    activated: 160,
    activatedPercent: 47.8,
    cohortGmv: 282000000,
  },
  {
    region: 'Jawa Timur',
    groupRegion: 'CPD',
    registered: 250,
    verified: 243,
    verifiedPercent: 97.2,
    pending: 7,
    slaBreachCount: 0,
    slaBreachPercent: 0.0,
    activated: 120,
    activatedPercent: 49.4,
    cohortGmv: 220000000,
  },
  {
    region: 'Banten',
    groupRegion: 'CPD',
    registered: 180,
    verified: 172,
    verifiedPercent: 95.6,
    pending: 8,
    slaBreachCount: 1,
    slaBreachPercent: 12.5,
    activated: 85,
    activatedPercent: 49.4,
    cohortGmv: 155000000,
  },
  {
    region: 'DI Yogyakarta',
    groupRegion: 'CPD',
    registered: 70,
    verified: 68,
    verifiedPercent: 97.1,
    pending: 2,
    slaBreachCount: 0,
    slaBreachPercent: 0.0,
    activated: 32,
    activatedPercent: 47.1,
    cohortGmv: 58000000,
  },
  {
    region: 'Sumatera Utara',
    groupRegion: 'BNN',
    registered: 210,
    verified: 188,
    verifiedPercent: 89.5,
    pending: 62,
    slaBreachCount: 18,
    slaBreachPercent: 29.0,
    activated: 75,
    activatedPercent: 39.9,
    cohortGmv: 185000000,
  },
  {
    region: 'Sumatera Selatan',
    groupRegion: 'BNN',
    registered: 160,
    verified: 142,
    verifiedPercent: 88.8,
    pending: 45,
    slaBreachCount: 14,
    slaBreachPercent: 31.1,
    activated: 58,
    activatedPercent: 40.8,
    cohortGmv: 140000000,
  },
  {
    region: 'Riau & Kepri',
    groupRegion: 'BNN',
    registered: 110,
    verified: 98,
    verifiedPercent: 89.1,
    pending: 28,
    slaBreachCount: 8,
    slaBreachPercent: 28.6,
    activated: 42,
    activatedPercent: 42.9,
    cohortGmv: 98000000,
  },
  {
    region: 'Lampung',
    groupRegion: 'BNN',
    registered: 90,
    verified: 82,
    verifiedPercent: 91.1,
    pending: 20,
    slaBreachCount: 5,
    slaBreachPercent: 25.0,
    activated: 35,
    activatedPercent: 42.7,
    cohortGmv: 78000000,
  },
  {
    region: 'Kalimantan Barat',
    groupRegion: 'BNN',
    registered: 180,
    verified: 164,
    verifiedPercent: 91.1,
    pending: 58,
    slaBreachCount: 16,
    slaBreachPercent: 27.6,
    activated: 56,
    activatedPercent: 34.1,
    cohortGmv: 112000000,
  },
  {
    region: 'Kalimantan Timur',
    groupRegion: 'BNN',
    registered: 80,
    verified: 72,
    verifiedPercent: 90.0,
    pending: 22,
    slaBreachCount: 6,
    slaBreachPercent: 27.3,
    activated: 28,
    activatedPercent: 38.9,
    cohortGmv: 62000000,
  },
  {
    region: 'Sulawesi Selatan',
    groupRegion: 'BNN',
    registered: 70,
    verified: 62,
    verifiedPercent: 88.6,
    pending: 18,
    slaBreachCount: 5,
    slaBreachPercent: 27.8,
    activated: 24,
    activatedPercent: 38.7,
    cohortGmv: 52000000,
  },
  {
    region: 'Bali & Nusa Tenggara',
    groupRegion: 'BNN',
    registered: 60,
    verified: 54,
    verifiedPercent: 90.0,
    pending: 12,
    slaBreachCount: 2,
    slaBreachPercent: 16.7,
    activated: 20,
    activatedPercent: 37.0,
    cohortGmv: 42000000,
  },
]

export const mockSellingAgents: SellingAgentRecord[] = [
  {
    agentId: 'SA-01',
    agentName: 'PT Bangun Prima Sejahtera',
    region: 'Jawa Barat',
    groupRegion: 'CPD',
    assignedVerifiedStores: 380,
    activatedStores: 260,
    activationRate: 68.4,
    cohortGmv: 390500000,
    avgGmvPerActiveBuyer: 1501923,
  },
  {
    agentId: 'SA-02',
    agentName: 'PT Cipta Sarana Mandiri',
    region: 'DKI Jakarta',
    groupRegion: 'CPD',
    assignedVerifiedStores: 290,
    activatedStores: 195,
    activationRate: 67.2,
    cohortGmv: 340000000,
    avgGmvPerActiveBuyer: 1743589,
  },
  {
    agentId: 'SA-03',
    agentName: 'PT Sinar Distribusi Nusantara',
    region: 'Jawa Tengah',
    groupRegion: 'CPD',
    assignedVerifiedStores: 280,
    activatedStores: 175,
    activationRate: 62.5,
    cohortGmv: 260000000,
    avgGmvPerActiveBuyer: 1485714,
  },
  {
    agentId: 'SA-04',
    agentName: 'PT Mega Niaga Utama',
    region: 'Jawa Timur',
    groupRegion: 'CPD',
    assignedVerifiedStores: 240,
    activatedStores: 150,
    activationRate: 62.5,
    cohortGmv: 230000000,
    avgGmvPerActiveBuyer: 1533333,
  },
  {
    agentId: 'SA-05',
    agentName: 'PT Karya Bersama Abadi',
    region: 'Sumatera Utara',
    groupRegion: 'BNN',
    assignedVerifiedStores: 180,
    activatedStores: 88,
    activationRate: 48.9,
    cohortGmv: 155000000,
    avgGmvPerActiveBuyer: 1761363,
  },
  {
    agentId: 'SA-06',
    agentName: 'PT Sumber Abadi Rezeki',
    region: 'Kalimantan Barat',
    groupRegion: 'BNN',
    assignedVerifiedStores: 160,
    activatedStores: 65,
    activationRate: 40.6,
    cohortGmv: 110000000,
    avgGmvPerActiveBuyer: 1692307,
  },
  {
    agentId: 'SA-07',
    agentName: 'PT Mitra Distribusi Jaya',
    region: 'Sumatera Selatan',
    groupRegion: 'BNN',
    assignedVerifiedStores: 140,
    activatedStores: 60,
    activationRate: 42.9,
    cohortGmv: 98000000,
    avgGmvPerActiveBuyer: 1633333,
  },
  {
    agentId: 'SA-08',
    agentName: 'PT Cahaya Inti Sejahtera',
    region: 'Sulawesi Selatan',
    groupRegion: 'BNN',
    assignedVerifiedStores: 60,
    activatedStores: 24,
    activationRate: 40.0,
    cohortGmv: 52000000,
    avgGmvPerActiveBuyer: 2166666,
  },
]

export const mockGrowthAnomalyAlerts: GrowthAnomalyAlert[] = [
  {
    id: 'ALT-01',
    severity: 'CRITICAL',
    title: 'High Pending SLA Breaches in Sumatera Utara & Selatan',
    impactLabel: '32 Stores >24h',
    rootCause: 'Manual verification backlog without tokocodeidcpd in BNN regions.',
    recommendation: 'Prioritaskan verifikasi manual & mapping agent untuk toko BNN Sumatera.',
    actionLabel: 'Buka Verification Queue',
  },
  {
    id: 'ALT-02',
    severity: 'WARNING',
    title: 'First-Order Conversion Lag in Kalimantan Barat',
    impactLabel: '34.1% Activation (Lagging)',
    rootCause: 'Tingkat aktivasi order perdana di Kalbar hanya 34.1%, tertinggal dibandingkan rata-rata 43.0%.',
    recommendation: 'Kirimkan reminder voucher aktivasi perdana melalui Selling Agent Kalbar.',
    actionLabel: 'Trigger Agent Outreach',
  },
]
